<?php declare(strict_types=1);


namespace App\Controllers;


use App\Common\RestController;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

/**
 * websocket
 *
 * Class Websocket
 * @package App\Controllers
 */
class Websocket extends RestController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    /**
     * Notes: 绑定客户端id和用户id
     *
     * Author: chentulin
     * DateTime: 2021/3/5 17:25
     * E-MAIL: <chentulinys@163.com>
     */
    public function bind()
    {

    }
}