<?php declare(strict_types=1);


namespace App\Controllers;


use App\Common\RestController;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use GatewayClient\Gateway;
use Psr\Log\LoggerInterface;

/**
 * websocket
 *
 * Class Websocket
 * @package App\Controllers
 */
class Websocket extends RestController
{
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    /**
     * Notes: 绑定客户端id和用户id
     *
     * Author: chentulin
     * DateTime: 2021/3/5 17:25
     * E-MAIL: <chentulinys@163.com>
     */
    public function bind()
    {
        $data = $this->request->getGet();
        if (isset($data['client_id'])) {
            $this->respondApi(['code' => 10009, '无法获取参数id']);
        }
        Gateway::$registerAddress = '120.78.13.233:1238';
        $client_id = $data['client_id'];
        $uid = 3;
        Gateway::bindUid($client_id, $uid);
//        Gateway::sendToUid($uid, '{"type":"sendMessage","to_client_id":"'. $client_id .'","content":"连接成功"}');
    }
}